GET http://localhost:3000/users

### Create a user
POST http://localhost:3000/users/ HTTP/1.1
content-type: application/json

{
    "firstName": "Adam",
    "lastName": "Sandler",
    "birthday": "05/23/1977",
    "email": "adam@example.com",
    "userName": "Bob Barker",
    "password": "Bb123456",
    "preferredGenre": "Adult"
}

###UPDATE a book
PUT http://localhost:3000/books/664bfd812c7a1f26080ac41d
content-type: application/json

{
    "title": "Where the Red Fern Grows",
    "authorFirstName": "Wilson",
    "authorLastName": "Rawls",
    "publishDate": 1961-01-01T00:00:00.000+00:00,
    "pages": 272,
    "age": "Grades 5-8",
    "rating": 5,
    "genre": "Children"
}

### Display one book
GET http://localhost:3000/books/664bfd812c7a1f26080ac41d

